// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6pJvdV8f1Bthu21gmovTRZwT51I7ne54',
    appId: '1:191949590375:web:911233e6ed273e54cde9c2',
    messagingSenderId: '191949590375',
    projectId: 'socialmediapp',
    authDomain: 'socialmediapp-1c9bd.firebaseapp.com',
    storageBucket: 'socialmediapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJbDUYP6Yyp-IkLvHreHa_QL7Jzk55fos',
    appId: '1:191949590375:android:960abda02da5203fcde9c2',
    messagingSenderId: '191949590375',
    projectId: 'socialmediapp',
    storageBucket: 'socialmediapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2M9XHbbM-XNYoNki3WsFDLOUO5ntfEjM',
    appId: '1:191949590375:ios:3bbd9430e591b835cde9c2',
    messagingSenderId: '191949590375',
    projectId: 'socialmediapp',
    storageBucket: 'socialmediapp.appspot.com',
    iosClientId: '191949590375-iglnvddjims8vnnq1e0fqem84gg6a9s1.apps.googleusercontent.com',
    iosBundleId: 'com.example.socially',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2M9XHbbM-XNYoNki3WsFDLOUO5ntfEjM',
    appId: '1:191949590375:ios:3652718c19312f18cde9c2',
    messagingSenderId: '191949590375',
    projectId: 'socialmediapp',
    storageBucket: 'socialmediapp.appspot.com',
    iosClientId: '191949590375-ldipmtkmeomb2e3i4r2lruj00tkqsul7.apps.googleusercontent.com',
    iosBundleId: 'com.example.socially.RunnerTests',
  );
}
